language: node_js
node_js:
- '0.12'
before_script: 
install: true
script:
- npm install grunt-cli -g
- npm install
- grunt travis
after_success:
- node deploy-docs.js
notifications:
  slack:
    secure: aQXFk2/MxX5eR2JM90xWAA9YX03QArY1ejUmnP/NkFHbB4zzKZblACjEeDTDTDCThZpXhrganX2nDWrWFrrXbOG28wKrRhEZSULPAgyiWGpfkMoT44fKmgh+eZ5C/isMF2eeQCrYo3EQCMxfCKxNaBhyLc+jr/Sm232zU2LaXo8=
