sudo: false
language: node_js
addons:
  chrome: stable
node_js:
  - '10'
cache:
  directories:
    - node_modules
    - node_cache
    - $HOME/.npm
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - gem install sass -v 3.4.24
  - npm i -g npm@6.12.0
script:
  - npm run travis
after_success:
  - node deploy-docs.js
  - if [[ "$TRAVIS_PULL_REQUEST" = "false" && ( "$TRAVIS_BRANCH" = "master" || "$TRAVIS_TAG" != "" ) ]]; then node_modules/.bin/grunt dists; fi
notifications:
  slack:
    secure: aQXFk2/MxX5eR2JM90xWAA9YX03QArY1ejUmnP/NkFHbB4zzKZblACjEeDTDTDCThZpXhrganX2nDWrWFrrXbOG28wKrRhEZSULPAgyiWGpfkMoT44fKmgh+eZ5C/isMF2eeQCrYo3EQCMxfCKxNaBhyLc+jr/Sm232zU2LaXo8=
